"""`detect` tests, including the P1-1 gate.

Review #2 named the gate: *"the determinism CI currently proves that sorting
strings is deterministic, not that building a lockfile from a filesystem is."*
So these tests build from a real fixture tree on disk, where dirent ordering,
NFD paths, symlinks, and size caps actually enter.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import unicodedata
from pathlib import Path

import pytest

from svarupa.detect import FileRole, ScanLimits, detect
from svarupa.lock import collision_check


def write(root: Path, rel: str, text: str = "x = 1\n") -> Path:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf8")
    return p


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A tree that exercises every classification branch."""
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "src/api/main.py")
    write(r, "src/api/routes.py")
    write(r, "src/auth/jwt.py")
    write(r, "web/app.ts")
    write(r, "web/util.tsx")
    write(r, "schema/init.sql", "CREATE TABLE t (id int);\n")
    write(r, "docker-compose.yml", "services:\n  api:\n    image: x\n")
    write(r, "pyproject.toml", "[project]\nname='x'\n")
    # excluded roles
    write(r, "tests/test_api.py")
    write(r, "src/api/routes_test.py")
    write(r, "web/app.spec.ts")
    write(r, "src/pb/thing_pb2.py")
    write(r, "vendor/lib/dep.py")
    write(r, "src/generated/client.py")
    write(r, "src/banner.py", "# Code generated by protoc. DO NOT EDIT.\nx = 1\n")
    # never walked
    write(r, "node_modules/pkg/index.js")
    write(r, ".venv/lib/thing.py")
    write(r, "dist/bundle.js")
    return r


# --------------------------------------------------------------------------
# Classification
# --------------------------------------------------------------------------


def roles(repo: Path) -> dict[str, FileRole]:
    return {f.path: f.role for f in detect(repo).files}


def test_source_files_are_source(repo: Path) -> None:
    r = roles(repo)
    for p in ("src/api/main.py", "src/auth/jwt.py", "web/app.ts", "web/util.tsx"):
        assert r[p] is FileRole.SOURCE, p


@pytest.mark.parametrize(
    ("path", "role"),
    [
        ("tests/test_api.py", FileRole.TEST),
        ("src/api/routes_test.py", FileRole.TEST),
        ("web/app.spec.ts", FileRole.TEST),
        ("src/pb/thing_pb2.py", FileRole.GENERATED),
        ("src/generated/client.py", FileRole.GENERATED),
        ("src/banner.py", FileRole.GENERATED),
        ("vendor/lib/dep.py", FileRole.VENDORED),
        ("docker-compose.yml", FileRole.CONFIG),
        ("pyproject.toml", FileRole.CONFIG),
    ],
)
def test_role_classification(repo: Path, path: str, role: FileRole) -> None:
    assert roles(repo)[path] is role


def test_generated_banner_is_detected_by_content(repo: Path) -> None:
    """`src/banner.py` has an innocent name; only the banner gives it away."""
    assert roles(repo)["src/banner.py"] is FileRole.GENERATED


def test_excluded_directories_are_never_walked(repo: Path) -> None:
    paths = {f.path for f in detect(repo).files}
    assert not any(p.startswith(("node_modules/", ".venv/", "dist/")) for p in paths)


def test_only_source_and_config_reach_architecture(repo: Path) -> None:
    """S5: test, generated and vendored code is 30-50% of files and imports
    everything. It stays in the graph but must not shape architecture."""
    arch = {f.path for f in detect(repo).architecture_files}
    assert "src/api/main.py" in arch
    assert "docker-compose.yml" in arch
    for excluded in (
        "tests/test_api.py",
        "src/pb/thing_pb2.py",
        "vendor/lib/dep.py",
        "src/generated/client.py",
    ):
        assert excluded not in arch, excluded


def test_language_detection(repo: Path) -> None:
    langs = dict(detect(repo).languages())
    assert langs["python"] >= 4
    assert langs["typescript"] >= 2
    assert langs["sql"] == 1


# --------------------------------------------------------------------------
# Ignore files
# --------------------------------------------------------------------------


def test_gitignore_is_honoured(repo: Path) -> None:
    (repo / ".gitignore").write_text("web/\n*.sql\n")
    paths = {f.path for f in detect(repo).files}
    assert not any(p.startswith("web/") for p in paths)
    assert "schema/init.sql" not in paths
    assert "src/api/main.py" in paths


def test_svarupaignore_is_honoured(repo: Path) -> None:
    (repo / ".svarupaignore").write_text("src/auth/\n")
    paths = {f.path for f in detect(repo).files}
    assert "src/auth/jwt.py" not in paths
    assert "src/api/main.py" in paths


def test_negation_cannot_reinstate_under_an_excluded_directory(repo: Path) -> None:
    """Matches git, deliberately.

    gitignore: "It is not possible to re-include a file if a parent directory
    of that file is excluded." We skip recursion into an ignored directory, so
    the negation is never reconsidered -- which is exactly git's behaviour and
    the reason it is cheap.
    """
    (repo / ".gitignore").write_text("src/api/\n!src/api/main.py\n")
    paths = {f.path for f in detect(repo).files}
    assert "src/api/main.py" not in paths
    assert "src/api/routes.py" not in paths
    assert "src/auth/jwt.py" in paths


def test_negation_works_for_a_file_pattern(repo: Path) -> None:
    (repo / ".gitignore").write_text("*.ts\n!web/app.ts\n")
    paths = {f.path for f in detect(repo).files}
    assert "web/app.ts" in paths
    assert "web/util.tsx" in paths  # .tsx is not matched by *.ts


# --------------------------------------------------------------------------
# Safety
# --------------------------------------------------------------------------


def test_symlink_outside_root_is_diagnosed_and_not_followed(repo: Path, tmp_path: Path) -> None:
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "secret.py").write_text("SECRET = 1\n")
    try:
        (repo / "link").symlink_to(outside, target_is_directory=True)
    except (OSError, NotImplementedError):
        pytest.skip("symlinks unavailable")

    scan = detect(repo)
    assert not any(f.path.startswith("link/") for f in scan.files)
    codes = {d.code for d in scan.diagnostics}
    assert "SVA-D-001" in codes, "escaping symlink must be diagnosed, not silently skipped"


def test_symlink_loop_does_not_hang(repo: Path) -> None:
    try:
        (repo / "src" / "loop").symlink_to(repo / "src", target_is_directory=True)
    except (OSError, NotImplementedError):
        pytest.skip("symlinks unavailable")
    scan = detect(repo)  # must terminate
    assert not any("/loop/" in f.path for f in scan.files)


def test_oversized_files_are_skipped_with_a_diagnostic(repo: Path) -> None:
    write(repo, "src/huge.py", "# pad\n" * 5000)
    scan = detect(repo, ScanLimits(max_file_bytes=1000))
    assert "src/huge.py" not in {f.path for f in scan.files}
    assert "SVA-D-002" in {d.code for d in scan.diagnostics}


def test_file_cap_reports_an_incomplete_scan(repo: Path) -> None:
    scan = detect(repo, ScanLimits(max_files=3))
    assert len(scan.files) == 3
    assert "SVA-D-003" in {d.code for d in scan.diagnostics}, (
        "a truncated scan must say so; silently partial results are worse than failing"
    )


def test_unreadable_directory_is_reported_not_fatal(repo: Path) -> None:
    if os.name != "posix" or os.geteuid() == 0:
        pytest.skip("needs posix and a non-root user")
    locked = repo / "src" / "locked"
    locked.mkdir()
    (locked / "a.py").write_text("x = 1\n")
    locked.chmod(0o000)
    try:
        scan = detect(repo)
        assert "SVA-D-005" in {d.code for d in scan.diagnostics}
        assert any(f.path == "src/api/main.py" for f in scan.files), "scan must continue"
    finally:
        locked.chmod(0o755)


# --------------------------------------------------------------------------
# Workspaces: the source of structural module identity
# --------------------------------------------------------------------------


def test_pnpm_workspace_detected(repo: Path) -> None:
    (repo / "pnpm-workspace.yaml").write_text("packages:\n  - 'packages/*'\n")
    kinds = {w.kind for w in detect(repo).workspaces}
    assert "pnpm" in kinds


def test_npm_workspace_detected_only_when_declared(repo: Path) -> None:
    write(repo, "package.json", '{"name":"x"}')
    assert "npm" not in {w.kind for w in detect(repo).workspaces}
    write(repo, "package.json", '{"name":"x","workspaces":["packages/*"]}')
    assert "npm" in {w.kind for w in detect(repo).workspaces}


def test_cargo_and_go_workspaces_detected(repo: Path) -> None:
    write(repo, "Cargo.toml", "[workspace]\nmembers = ['a']\n")
    write(repo, "go.work", "go 1.22\nuse ./a\n")
    kinds = {w.kind for w in detect(repo).workspaces}
    assert {"cargo", "go"} <= kinds


# --------------------------------------------------------------------------
# THE P1-1 GATE: determinism from a real filesystem
# --------------------------------------------------------------------------


@pytest.mark.determinism
def test_scan_is_byte_stable_across_repeated_runs(repo: Path) -> None:
    runs = [tuple(detect(repo).files) for _ in range(10)]
    assert len(set(runs)) == 1


@pytest.mark.determinism
def test_scan_order_is_independent_of_creation_order(tmp_path: Path) -> None:
    """Dirent order is filesystem-dependent and must never leak.

    Two trees with identical contents created in opposite orders must scan
    identically. On many filesystems creation order *is* dirent order, so this
    would fail against an unsorted `os.scandir`.
    """
    names = ["zeta.py", "alpha.py", "mid.py", "Beta.py", "_under.py"]
    a, b = tmp_path / "a", tmp_path / "b"
    for root, order in ((a, names), (b, list(reversed(names)))):
        root.mkdir()
        for n in order:
            write(root, f"src/{n}")

    fa = [f.path for f in detect(a).files]
    fb = [f.path for f in detect(b).files]
    assert fa == fb == sorted(fa)


@pytest.mark.determinism
def test_nfd_paths_on_disk_are_normalized(tmp_path: Path) -> None:
    """The real filesystem leg of the NFC guard.

    A directory created with explicit NFD bytes must scan as NFC, or two
    machines produce two different lockfiles for the same tree.
    """
    r = tmp_path / "repo"
    r.mkdir()
    nfd = unicodedata.normalize("NFD", "café")
    write(r, f"src/{nfd}/mod.py")
    write(r, "src/plain/mod.py")

    scan = detect(r)
    assert len(scan.files) == 2
    for f in scan.files:
        assert unicodedata.is_normalized("NFC", f.path), f"{f.path!r} is not NFC"


@pytest.mark.determinism
def test_content_hash_tracks_content_not_metadata(repo: Path) -> None:
    before = {f.path: f.content_hash for f in detect(repo).files}
    os.utime(repo / "src/api/main.py", (0, 0))  # touch mtime only
    after = {f.path: f.content_hash for f in detect(repo).files}
    assert before == after, "mtime must not affect the hash"

    write(repo, "src/api/main.py", "x = 2\n")
    changed = {f.path: f.content_hash for f in detect(repo).files}
    assert changed["src/api/main.py"] != before["src/api/main.py"]
    assert changed["src/auth/jwt.py"] == before["src/auth/jwt.py"], "locality"


@pytest.mark.determinism
def test_absolute_path_of_the_repo_never_leaks(tmp_path: Path) -> None:
    """The same tree at two locations must scan identically.

    An absolute path leaking into a record would make the lockfile depend on
    where the repo happens to be checked out.
    """
    for name in ("here", "somewhere/else/deeper"):
        d = tmp_path / name
        d.mkdir(parents=True)
        write(d, "src/a.py")
        write(d, "src/b.py")

    one = tuple(detect(tmp_path / "here").files)
    two = tuple(detect(tmp_path / "somewhere/else/deeper").files)
    assert one == two


@pytest.mark.determinism
def test_visit_order_is_normalized_before_sorting(tmp_path: Path) -> None:
    """Regression: normalize BEFORE sorting, not after.

    `os.scandir` can return NFD on one machine and NFC on another for the same
    logical name, and the two sort differently: NFD "café" sorts before "cafz"
    while NFC "café" sorts after it. Sorting raw names therefore gives two
    machines different visit orders. That matters because `max_files`
    truncation keeps whichever files were reached first, so a capped scan would
    retain different file sets.
    """
    nfd, nfc = unicodedata.normalize("NFD", "café"), unicodedata.normalize("NFC", "café")
    assert nfd != nfc

    a, b = tmp_path / "a", tmp_path / "b"
    for root, spelling in ((a, nfd), (b, nfc)):
        root.mkdir()
        for n in ("cafz.py", f"{spelling}.py", "cag.py"):
            write(root, f"src/{n}")

    # Cap below the file count, so which files survive depends on visit order.
    limits = ScanLimits(max_files=2)
    kept_a = [f.path for f in detect(a, limits).files]
    kept_b = [f.path for f in detect(b, limits).files]
    assert kept_a == kept_b, "capped scan kept different files depending on NFD vs NFC"


def test_collision_detection_runs_per_sibling_set_on_raw_names() -> None:
    """Platform-independent, unlike the version this replaces.

    That one built two directories on disk and asserted a diagnostic. It
    skipped on case-insensitive APFS -- the only platform it was ever run on --
    and failed on every Linux CI job, because `collision_check` was being given
    whole paths whose parent components had already been normalized. Two
    colliding sibling directories with differently-named children never share
    a path key, so nothing was ever detected.

    Detection is component-wise on raw sibling names, so it is testable without
    needing a filesystem that can hold both spellings.
    """
    nfd = unicodedata.normalize("NFD", "café")
    nfc = unicodedata.normalize("NFC", "café")

    assert [d.code for d in collision_check(["Utils", "utils"])] == ["SVA-L-004"]
    assert [d.code for d in collision_check([nfd, nfc])] == ["SVA-L-004"]
    assert collision_check(["api", "auth", "billing"]) == []


def test_case_collision_is_diagnosed_on_disk(tmp_path: Path) -> None:
    """The on-disk leg. Skips where the filesystem cannot represent it."""
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "src/Utils/a.py")
    write(r, "src/utils/b.py")
    if len({p.name for p in (r / "src").iterdir()}) < 2:
        pytest.skip("case-insensitive filesystem; both paths are one directory here")

    codes = {d.code for d in detect(r).diagnostics}
    assert "SVA-L-004" in codes, "case collision must be diagnosed, never silently merged"


# --------------------------------------------------------------------------
# Regressions from review #3
# --------------------------------------------------------------------------


def test_exact_file_count_is_not_reported_as_truncated(tmp_path: Path) -> None:
    """A repo with exactly max_files files is a COMPLETE scan.

    The diagnostic used to restate the pre-append condition rather than check
    whether anything was actually dropped, so it claimed a partial scan on a
    complete one. A tool whose pitch is verified claims must not make a false
    claim about its own scan.
    """
    r = tmp_path / "repo"
    r.mkdir()
    for n in "abc":
        write(r, f"src/{n}.py")
    scan = detect(r, ScanLimits(max_files=3))
    assert len(scan.files) == 3
    assert "SVA-D-003" not in {d.code for d in scan.diagnostics}


def test_one_bad_ignore_pattern_does_not_disable_the_rest(tmp_path: Path) -> None:
    """Compiling the whole list at once meant a typo dropped every pattern.

    pathspec raises for a trailing backslash or a bare "!". The old code caught
    it, left the spec None, and silently ignored nothing at all -- letting
    ignored files, possibly secrets, into the graph with no diagnostic.
    """
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "src/a.py")
    write(r, "secret/token.py")
    (r / ".gitignore").write_text("secret/\nfoo\\\n")

    scan = detect(r)
    paths = {f.path for f in scan.files}
    assert "secret/token.py" not in paths, "a valid pattern must still apply"
    assert "src/a.py" in paths
    assert "SVA-D-006" in {d.code for d in scan.diagnostics}, "the bad line must be reported"


@pytest.mark.parametrize(
    ("manifest", "content"),
    [
        (
            "pyproject.toml",
            "[tool.poetry]\nname='x'\n[tool.poetry.group.dev.dependencies]\np='*'\n",
        ),
        ("Cargo.toml", "# we moved [workspace] to the parent\n[package]\nname='x'\n"),
        ("package.json", '{"name":"x","keywords":["workspaces","monorepo"]}'),
    ],
)
def test_workspace_detection_does_not_false_positive(
    tmp_path: Path, manifest: str, content: str
) -> None:
    """Manifests are parsed, never substring-matched.

    Poetry dependency groups appear in essentially every modern Poetry project
    and are not workspaces. A false workspace root becomes a false module
    boundary, and module identity is what the lockfile is keyed on.
    """
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "src/a.py")
    (r / manifest).write_text(content)
    assert detect(r).workspaces == ()


@pytest.mark.parametrize(
    ("manifest", "content", "kind"),
    [
        ("pyproject.toml", "[tool.uv.workspace]\nmembers=['pkgs/*']\n", "uv"),
        ("Cargo.toml", "[workspace]\nmembers=['a']\n", "cargo"),
        ("package.json", '{"name":"x","workspaces":["pkgs/*"]}', "npm"),
    ],
)
def test_real_workspaces_are_still_detected(
    tmp_path: Path, manifest: str, content: str, kind: str
) -> None:
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "src/a.py")
    (r / manifest).write_text(content)
    assert {w.kind for w in detect(r).workspaces} == {kind}


@pytest.mark.parametrize(
    ("name", "body"),
    [
        ("cleanup.py", "# remove autogenerated artifacts from dist/\nx = 1\n"),
        ("lint.py", '"""Checks that files marked DO NOT EDIT are untouched."""\nx = 1\n'),
    ],
)
def test_files_that_merely_mention_generation_are_not_generated(
    tmp_path: Path, name: str, body: str
) -> None:
    """Banner sniffing matched anywhere in the first 2KB, case-insensitively.

    Any tooling script that talks *about* generated files silently vanished
    from architecture.
    """
    r = tmp_path / "repo"
    r.mkdir()
    write(r, f"scripts/{name}", body)
    roles = {f.path: f.role for f in detect(r).files}
    assert roles[f"scripts/{name}"] is FileRole.SOURCE


@pytest.mark.parametrize(
    "banner",
    [
        "// Code generated by protoc-gen-go. DO NOT EDIT.\n",
        "# @generated by thing\n",
        "# DO NOT EDIT\n",
    ],
)
def test_real_banners_are_still_caught(tmp_path: Path, banner: str) -> None:
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "src/thing.py", banner + "x = 1\n")
    roles = {f.path: f.role for f in detect(r).files}
    assert roles["src/thing.py"] is FileRole.GENERATED


def test_fixtures_is_a_domain_noun_not_a_test_marker(tmp_path: Path) -> None:
    """A sports app has fixtures. A data pipeline has fixtures."""
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "src/fixtures/loader.py")
    write(r, "tests/fixtures/sample.py")
    roles = {f.path: f.role for f in detect(r).files}
    assert roles["src/fixtures/loader.py"] is FileRole.SOURCE
    assert roles["tests/fixtures/sample.py"] is FileRole.TEST, "still caught under tests/"


def test_sql_migrations_stay_in_architecture(tmp_path: Path) -> None:
    """Django and Alembic migrations are often the only DDL in the repo.

    Design 4.3 names *.sql the ERD source of truth, so excluding them as
    generated would make the ERD deriver honestly return None for a codebase
    that has a complete schema.
    """
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "db/migrations/001_init.sql", "CREATE TABLE t (id int);\n")
    write(r, "db/migrations/0002_auto.py", "x = 1\n")
    roles = {f.path: f.role for f in detect(r).files}
    assert roles["db/migrations/001_init.sql"] is FileRole.CONFIG
    assert roles["db/migrations/0002_auto.py"] is FileRole.GENERATED


# --------------------------------------------------------------------------
# git parity oracle
#
# Review #3's riskiest remaining assumption: "in-process pathspec matching over
# a root-only pattern list reproduces git's view of the repository."
#
# The production rule against shelling out to git is correct -- the file set
# must not depend on whether git is installed. But nothing stops the TEST suite
# from using `git ls-files` as an oracle, which is the only way that claim gets
# weighed at all.
# --------------------------------------------------------------------------


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, text=True, check=True
    ).stdout


def _git_visible(repo: Path) -> set[str]:
    """What git considers part of the repo: tracked plus untracked-not-ignored."""
    out = _git(
        repo,
        "-c",
        "core.quotepath=false",
        "ls-files",
        "-z",
        "--cached",
        "--others",
        "--exclude-standard",
    )
    return {p for p in out.split("\0") if p}


@pytest.fixture
def git_repo(tmp_path: Path) -> Path:
    if not shutil.which("git"):
        pytest.skip("git unavailable")
    r = tmp_path / "repo"
    r.mkdir()
    _git(r, "init", "-q")
    _git(r, "config", "user.email", "t@t.t")
    _git(r, "config", "user.name", "t")
    return r


def test_matches_git_on_root_patterns_and_file_negation(git_repo: Path) -> None:
    write(git_repo, "src/a.py")
    write(git_repo, "src/b.py")
    write(git_repo, "build/out.py")
    write(git_repo, "tools/helper.py")
    (git_repo / ".gitignore").write_text("build/\ntools/*.py\n!tools/helper.py\n")

    ours = {f.path for f in detect(git_repo).files}
    theirs = {p for p in _git_visible(git_repo) if p.endswith(".py")}
    assert ours == theirs, (
        f"diverged from git: only-ours={ours - theirs} only-git={theirs - ours}"
    )


@pytest.mark.xfail(
    reason=(
        "pathspec diverges from git on directory negation. Given '*.py' then "
        "'!keep/', git still ignores keep/important.py, because un-ignoring a "
        "directory does not un-ignore files inside it that another pattern "
        "matches. pathspec reports it visible. Verified against real git "
        "check-ignore. Strict, so this goes red if pathspec ever changes."
    ),
    strict=True,
)
def test_pathspec_diverges_from_git_on_directory_negation(git_repo: Path) -> None:
    write(git_repo, "src/a.py")
    write(git_repo, "keep/important.py")
    (git_repo / ".gitignore").write_text("*.py\n!src/*.py\n!keep/\n")

    ours = {f.path for f in detect(git_repo).files}
    theirs = {p for p in _git_visible(git_repo) if p.endswith(".py")}
    assert ours == theirs


@pytest.mark.xfail(
    reason="nested .gitignore files are not yet honoured (review #3 F5); "
    "this oracle documents the exact divergence rather than hiding it",
    strict=True,
)
def test_matches_git_on_nested_gitignore(git_repo: Path) -> None:
    """Real repos carry per-directory .gitignore files.

    git applies each relative to its own directory. We read only the root pair,
    so files git ignores currently enter the graph. Marked strict-xfail so it
    turns red the moment F5 is fixed and this becomes a passing guarantee.
    """
    write(git_repo, "src/a.py")
    write(git_repo, "src/nested/keepme.py")
    write(git_repo, "src/nested/skipme.py")
    (git_repo / "src" / "nested" / ".gitignore").write_text("skipme.py\n")

    ours = {f.path for f in detect(git_repo).files}
    theirs = {p for p in _git_visible(git_repo) if p.endswith(".py")}
    assert ours == theirs
