"""`detect` tests, including the P1-1 gate.

Review #2 named the gate: *"the determinism CI currently proves that sorting
strings is deterministic, not that building a lockfile from a filesystem is."*
So these tests build from a real fixture tree on disk, where dirent ordering,
NFD paths, symlinks, and size caps actually enter.
"""

from __future__ import annotations

import os
import unicodedata
from pathlib import Path

import pytest

from svarupa.detect import FileRole, ScanLimits, detect


def write(root: Path, rel: str, text: str = "x = 1\n") -> Path:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf8")
    return p


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A tree that exercises every classification branch."""
    r = tmp_path / "repo"
    r.mkdir()
    write(r, "src/api/main.py")
    write(r, "src/api/routes.py")
    write(r, "src/auth/jwt.py")
    write(r, "web/app.ts")
    write(r, "web/util.tsx")
    write(r, "schema/init.sql", "CREATE TABLE t (id int);\n")
    write(r, "docker-compose.yml", "services:\n  api:\n    image: x\n")
    write(r, "pyproject.toml", "[project]\nname='x'\n")
    # excluded roles
    write(r, "tests/test_api.py")
    write(r, "src/api/routes_test.py")
    write(r, "web/app.spec.ts")
    write(r, "src/pb/thing_pb2.py")
    write(r, "vendor/lib/dep.py")
    write(r, "src/generated/client.py")
    write(r, "src/banner.py", "# Code generated by protoc. DO NOT EDIT.\nx = 1\n")
    # never walked
    write(r, "node_modules/pkg/index.js")
    write(r, ".venv/lib/thing.py")
    write(r, "dist/bundle.js")
    return r


# --------------------------------------------------------------------------
# Classification
# --------------------------------------------------------------------------


def roles(repo: Path) -> dict[str, FileRole]:
    return {f.path: f.role for f in detect(repo).files}


def test_source_files_are_source(repo: Path) -> None:
    r = roles(repo)
    for p in ("src/api/main.py", "src/auth/jwt.py", "web/app.ts", "web/util.tsx"):
        assert r[p] is FileRole.SOURCE, p


@pytest.mark.parametrize(
    ("path", "role"),
    [
        ("tests/test_api.py", FileRole.TEST),
        ("src/api/routes_test.py", FileRole.TEST),
        ("web/app.spec.ts", FileRole.TEST),
        ("src/pb/thing_pb2.py", FileRole.GENERATED),
        ("src/generated/client.py", FileRole.GENERATED),
        ("src/banner.py", FileRole.GENERATED),
        ("vendor/lib/dep.py", FileRole.VENDORED),
        ("docker-compose.yml", FileRole.CONFIG),
        ("pyproject.toml", FileRole.CONFIG),
    ],
)
def test_role_classification(repo: Path, path: str, role: FileRole) -> None:
    assert roles(repo)[path] is role


def test_generated_banner_is_detected_by_content(repo: Path) -> None:
    """`src/banner.py` has an innocent name; only the banner gives it away."""
    assert roles(repo)["src/banner.py"] is FileRole.GENERATED


def test_excluded_directories_are_never_walked(repo: Path) -> None:
    paths = {f.path for f in detect(repo).files}
    assert not any(p.startswith(("node_modules/", ".venv/", "dist/")) for p in paths)


def test_only_source_and_config_reach_architecture(repo: Path) -> None:
    """S5: test, generated and vendored code is 30-50% of files and imports
    everything. It stays in the graph but must not shape architecture."""
    arch = {f.path for f in detect(repo).architecture_files}
    assert "src/api/main.py" in arch
    assert "docker-compose.yml" in arch
    for excluded in (
        "tests/test_api.py",
        "src/pb/thing_pb2.py",
        "vendor/lib/dep.py",
        "src/generated/client.py",
    ):
        assert excluded not in arch, excluded


def test_language_detection(repo: Path) -> None:
    langs = dict(detect(repo).languages())
    assert langs["python"] >= 4
    assert langs["typescript"] >= 2
    assert langs["sql"] == 1


# --------------------------------------------------------------------------
# Ignore files
# --------------------------------------------------------------------------


def test_gitignore_is_honoured(repo: Path) -> None:
    (repo / ".gitignore").write_text("web/\n*.sql\n")
    paths = {f.path for f in detect(repo).files}
    assert not any(p.startswith("web/") for p in paths)
    assert "schema/init.sql" not in paths
    assert "src/api/main.py" in paths


def test_svarupaignore_is_honoured(repo: Path) -> None:
    (repo / ".svarupaignore").write_text("src/auth/\n")
    paths = {f.path for f in detect(repo).files}
    assert "src/auth/jwt.py" not in paths
    assert "src/api/main.py" in paths


def test_negation_reinstates_a_file_when_its_parent_is_not_excluded() -> None:
    """Negation works at file level."""


def test_negation_cannot_reinstate_under_an_excluded_directory(repo: Path) -> None:
    """Matches git, deliberately.

    gitignore: "It is not possible to re-include a file if a parent directory
    of that file is excluded." We skip recursion into an ignored directory, so
    the negation is never reconsidered -- which is exactly git's behaviour and
    the reason it is cheap.
    """
    (repo / ".gitignore").write_text("src/api/\n!src/api/main.py\n")
    paths = {f.path for f in detect(repo).files}
    assert "src/api/main.py" not in paths
    assert "src/api/routes.py" not in paths
    assert "src/auth/jwt.py" in paths


def test_negation_works_for_a_file_pattern(repo: Path) -> None:
    (repo / ".gitignore").write_text("*.ts\n!web/app.ts\n")
    paths = {f.path for f in detect(repo).files}
    assert "web/app.ts" in paths
    assert "web/util.tsx" in paths  # .tsx is not matched by *.ts


# --------------------------------------------------------------------------
# Safety
# --------------------------------------------------------------------------


def test_symlink_outside_root_is_diagnosed_and_not_followed(repo: Path, tmp_path: Path) -> None:
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "secret.py").write_text("SECRET = 1\n")
    try:
        (repo / "link").symlink_to(outside, target_is_directory=True)
    except (OSError, NotImplementedError):
        pytest.skip("symlinks unavailable")

    scan = detect(repo)
    assert not any(f.path.startswith("link/") for f in scan.files)
    codes = {d.code for d in scan.diagnostics}
    assert "SVA-D-001" in codes, "escaping symlink must be diagnosed, not silently skipped"


def test_symlink_loop_does_not_hang(repo: Path) -> None:
    try:
        (repo / "src" / "loop").symlink_to(repo / "src", target_is_directory=True)
    except (OSError, NotImplementedError):
        pytest.skip("symlinks unavailable")
    scan = detect(repo)  # must terminate
    assert not any("/loop/" in f.path for f in scan.files)


def test_oversized_files_are_skipped_with_a_diagnostic(repo: Path) -> None:
    write(repo, "src/huge.py", "# pad\n" * 5000)
    scan = detect(repo, ScanLimits(max_file_bytes=1000))
    assert "src/huge.py" not in {f.path for f in scan.files}
    assert "SVA-D-002" in {d.code for d in scan.diagnostics}


def test_file_cap_reports_an_incomplete_scan(repo: Path) -> None:
    scan = detect(repo, ScanLimits(max_files=3))
    assert len(scan.files) == 3
    assert "SVA-D-003" in {d.code for d in scan.diagnostics}, (
        "a truncated scan must say so; silently partial results are worse than failing"
    )


def test_unreadable_directory_is_reported_not_fatal(repo: Path) -> None:
    if os.name != "posix" or os.geteuid() == 0:
        pytest.skip("needs posix and a non-root user")
    locked = repo / "src" / "locked"
    locked.mkdir()
    (locked / "a.py").write_text("x = 1\n")
    locked.chmod(0o000)
    try:
        scan = detect(repo)
        assert "SVA-D-005" in {d.code for d in scan.diagnostics}
        assert any(f.path == "src/api/main.py" for f in scan.files), "scan must continue"
    finally:
        locked.chmod(0o755)


# --------------------------------------------------------------------------
# Workspaces: the source of structural module identity
# --------------------------------------------------------------------------


def test_pnpm_workspace_detected(repo: Path) -> None:
    (repo / "pnpm-workspace.yaml").write_text("packages:\n  - 'packages/*'\n")
    kinds = {w.kind for w in detect(repo).workspaces}
    assert "pnpm" in kinds


def test_npm_workspace_detected_only_when_declared(repo: Path) -> None:
    write(repo, "package.json", '{"name":"x"}')
    assert "npm" not in {w.kind for w in detect(repo).workspaces}
    write(repo, "package.json", '{"name":"x","workspaces":["packages/*"]}')
    assert "npm" in {w.kind for w in detect(repo).workspaces}


def test_cargo_and_go_workspaces_detected(repo: Path) -> None:
    write(repo, "Cargo.toml", "[workspace]\nmembers = ['a']\n")
    write(repo, "go.work", "go 1.22\nuse ./a\n")
    kinds = {w.kind for w in detect(repo).workspaces}
    assert {"cargo", "go"} <= kinds


# --------------------------------------------------------------------------
# THE P1-1 GATE: determinism from a real filesystem
# --------------------------------------------------------------------------


@pytest.mark.determinism
def test_scan_is_byte_stable_across_repeated_runs(repo: Path) -> None:
    runs = [tuple(detect(repo).files) for _ in range(10)]
    assert len(set(runs)) == 1


@pytest.mark.determinism
def test_scan_order_is_independent_of_creation_order(tmp_path: Path) -> None:
    """Dirent order is filesystem-dependent and must never leak.

    Two trees with identical contents created in opposite orders must scan
    identically. On many filesystems creation order *is* dirent order, so this
    would fail against an unsorted `os.scandir`.
    """
    names = ["zeta.py", "alpha.py", "mid.py", "Beta.py", "_under.py"]
    a, b = tmp_path / "a", tmp_path / "b"
    for root, order in ((a, names), (b, list(reversed(names)))):
        root.mkdir()
        for n in order:
            write(root, f"src/{n}")

    fa = [f.path for f in detect(a).files]
    fb = [f.path for f in detect(b).files]
    assert fa == fb == sorted(fa)


@pytest.mark.determinism
def test_nfd_paths_on_disk_are_normalized(tmp_path: Path) -> None:
    """The real filesystem leg of the NFC guard.

    A directory created with explicit NFD bytes must scan as NFC, or two
    machines produce two different lockfiles for the same tree.
    """
    r = tmp_path / "repo"
    r.mkdir()
    nfd = unicodedata.normalize("NFD", "café")
    write(r, f"src/{nfd}/mod.py")
    write(r, "src/plain/mod.py")

    scan = detect(r)
    assert len(scan.files) == 2
    for f in scan.files:
        assert unicodedata.is_normalized("NFC", f.path), f"{f.path!r} is not NFC"


@pytest.mark.determinism
def test_content_hash_tracks_content_not_metadata(repo: Path) -> None:
    before = {f.path: f.content_hash for f in detect(repo).files}
    os.utime(repo / "src/api/main.py", (0, 0))  # touch mtime only
    after = {f.path: f.content_hash for f in detect(repo).files}
    assert before == after, "mtime must not affect the hash"

    write(repo, "src/api/main.py", "x = 2\n")
    changed = {f.path: f.content_hash for f in detect(repo).files}
    assert changed["src/api/main.py"] != before["src/api/main.py"]
    assert changed["src/auth/jwt.py"] == before["src/auth/jwt.py"], "locality"


@pytest.mark.determinism
def test_absolute_path_of_the_repo_never_leaks(tmp_path: Path) -> None:
    """The same tree at two locations must scan identically.

    An absolute path leaking into a record would make the lockfile depend on
    where the repo happens to be checked out.
    """
    for name in ("here", "somewhere/else/deeper"):
        d = tmp_path / name
        d.mkdir(parents=True)
        write(d, "src/a.py")
        write(d, "src/b.py")

    one = tuple(detect(tmp_path / "here").files)
    two = tuple(detect(tmp_path / "somewhere/else/deeper").files)
    assert one == two
